server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
    prefer-ip-address: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${server.port}/eureka/
  server:
    # Desactivar modo self-preservation en dev para evitar "zombies" si bajan servicios r√°pidamente
    enable-self-preservation: ${EUREKA_SELF_PRESERVATION:false}
    wait-time-in-ms-when-sync-empty: 0